Param(
  [string]$RepoRoot = (Resolve-Path "$PSScriptRoot\..\..").Path
)

$ErrorActionPreference = "Stop"
$outDir = Join-Path $RepoRoot "config"
$outFile = Join-Path $outDir "runtime.env"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

function Pick-CustomModel {
  $mfs = Get-ChildItem -Path $RepoRoot -Recurse -File -Filter "Modelfile" |
    Where-Object { $_.FullName -notmatch "\\.git\\" -and $_.FullName -notmatch "\\.venv\\" } |
    Select-Object -First 1
  if (-not $mfs) { return "" }

  $mf = $mfs.FullName
  $dir = Split-Path $mf -Parent
  $name = Split-Path $dir -Leaf

  $override = (Select-String -Path $mf -Pattern '^\s*#\s*NAME:\s*' -ErrorAction SilentlyContinue | Select-Object -First 1).Line
  if ($override) { $name = ($override -replace '^\s*#\s*NAME:\s*','').Trim() }
  return $name
}

$chat = Pick-CustomModel
$embed = $env:CITL_EMBED_MODEL
if (-not $embed) { $embed = "nomic-embed-text" }
$host = $env:OLLAMA_HOST
if (-not $host) { $host = "http://127.0.0.1:11434" }

@"
# Auto-generated by scripts/citl/write_runtime_env.ps1
export OLLAMA_HOST="$host"
export CITL_CHAT_MODEL="$chat"
export OLLAMA_MODEL="$chat"
export CHAT_MODEL="$chat"
export MODEL="$chat"
export CITL_EMBED_MODEL="$embed"
export OLLAMA_EMBED_MODEL="$embed"
export EMBED_MODEL="$embed"
"@ | Set-Content -Path $outFile -Encoding UTF8

Write-Host "[runtime] wrote: $outFile"
Get-Content $outFile
